// prisma/seedClients.ts
import { PrismaClient, Role, ExperienceLevel } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const CLIENTS = [
  // ─── PAKISTANI CLIENTS ───────────────────────────────
  {
    name: "Imran Siddiqui",
    email: "imran.siddiqui@skillbridge.dev",
    location: "Karachi, Pakistan",
    timezone: "Asia/Karachi",
    company: "NexaTech Solutions",
    companyType: "Startup",
    industry: "SaaS",
    bio: "Founder of a B2B SaaS startup building HR automation tools for Pakistani SMEs. Looking for reliable developers and designers.",
    website: "nexatech.pk",
    hiringPreference: "Fixed",
    budgetRange: "Medium",
    preferredExpLevel: ExperienceLevel.MID,
    commMethod: "Slack",
    availability: "Full-time",
  },
  {
    name: "Zara Hussain",
    email: "zara.hussain@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    company: "ZH Boutique",
    companyType: "Individual",
    industry: "E-commerce",
    bio: "Owner of an online fashion boutique scaling to international markets. Need help with Shopify store, digital marketing, and brand identity.",
    website: "zhboutique.com",
    hiringPreference: "Both",
    budgetRange: "Low",
    preferredExpLevel: ExperienceLevel.ENTRY,
    commMethod: "Chat",
    availability: "Part-time",
  },
  {
    name: "Tariq Jameel",
    email: "tariq.jameel@skillbridge.dev",
    location: "Islamabad, Pakistan",
    timezone: "Asia/Karachi",
    company: "FinEdge Pakistan",
    companyType: "Enterprise",
    industry: "Fintech",
    bio: "CTO at a fintech company building payment infrastructure for Pakistan's underbanked population. Hiring senior engineers and security specialists.",
    website: "finedge.pk",
    hiringPreference: "Hourly",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.EXPERT,
    commMethod: "Email",
    availability: "Full-time",
  },
  {
    name: "Sobia Rafiq",
    email: "sobia.rafiq@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    company: "LearnSpark",
    companyType: "Startup",
    industry: "EdTech",
    bio: "Co-founder of an EdTech startup democratizing quality education in Pakistan. Looking for mobile developers and UI/UX designers.",
    website: "learnspark.io",
    hiringPreference: "Fixed",
    budgetRange: "Medium",
    preferredExpLevel: ExperienceLevel.MID,
    commMethod: "Slack",
    availability: "Full-time",
  },
  {
    name: "Khalid Mehmood",
    email: "khalid.mehmood@skillbridge.dev",
    location: "Faisalabad, Pakistan",
    timezone: "Asia/Karachi",
    company: "TextilePro",
    companyType: "Enterprise",
    industry: "Manufacturing",
    bio: "Managing Director of a textile export company. Need ERP integration, inventory management systems, and a B2B client portal.",
    website: "textilepro.com.pk",
    hiringPreference: "Fixed",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.SENIOR,
    commMethod: "Email",
    availability: "Part-time",
  },
  {
    name: "Amna Yousuf",
    email: "amna.yousuf@skillbridge.dev",
    location: "Karachi, Pakistan",
    timezone: "Asia/Karachi",
    company: "HealthFirst",
    companyType: "Startup",
    industry: "Healthcare",
    bio: "CEO of a telemedicine startup connecting patients with doctors across Pakistan. Hiring backend developers, mobile developers, and data analysts.",
    website: "healthfirst.pk",
    hiringPreference: "Both",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.SENIOR,
    commMethod: "Slack",
    availability: "Full-time",
  },
  {
    name: "Bilal Chaudhry",
    email: "bilal.chaudhry@skillbridge.dev",
    location: "Rawalpindi, Pakistan",
    timezone: "Asia/Karachi",
    company: "PropVision",
    companyType: "Startup",
    industry: "Real Estate",
    bio: "Founder of a real estate tech platform. Need 3D visualization artists, web developers, and a digital marketing team.",
    website: "propvision.pk",
    hiringPreference: "Fixed",
    budgetRange: "Medium",
    preferredExpLevel: ExperienceLevel.MID,
    commMethod: "Chat",
    availability: "Full-time",
  },
  {
    name: "Nadia Chaudry",
    email: "nadia.chaudry@skillbridge.dev",
    location: "Multan, Pakistan",
    timezone: "Asia/Karachi",
    company: "FoodFlow",
    companyType: "Startup",
    industry: "Food & Beverage",
    bio: "Co-founder of a cloud kitchen management platform. Looking for React developers, mobile app developers, and UI designers.",
    website: "foodflow.pk",
    hiringPreference: "Hourly",
    budgetRange: "Medium",
    preferredExpLevel: ExperienceLevel.MID,
    commMethod: "Slack",
    availability: "Full-time",
  },
  {
    name: "Asim Raza",
    email: "asim.raza@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    company: "LogiTrack",
    companyType: "Enterprise",
    industry: "Logistics",
    bio: "Operations Director at a logistics company modernizing supply chain tracking across Pakistan. Need IoT developers, backend engineers, and data engineers.",
    website: "logitrack.pk",
    hiringPreference: "Both",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.EXPERT,
    commMethod: "Email",
    availability: "Full-time",
  },
  {
    name: "Fareeha Shah",
    email: "fareeha.shah@skillbridge.dev",
    location: "Islamabad, Pakistan",
    timezone: "Asia/Karachi",
    company: "GreenEnergy PK",
    companyType: "Enterprise",
    industry: "Clean Energy",
    bio: "Project Manager at a solar energy company. Need IoT developers for smart meter solutions, a website redesign, and marketing content.",
    website: "greenenergy.pk",
    hiringPreference: "Fixed",
    budgetRange: "Medium",
    preferredExpLevel: ExperienceLevel.MID,
    commMethod: "Email",
    availability: "Part-time",
  },

  // ─── AMERICAN CLIENTS ────────────────────────────────
  {
    name: "Jason Miller",
    email: "jason.miller@skillbridge.dev",
    location: "San Francisco, CA, USA",
    timezone: "America/Los_Angeles",
    company: "Velocity AI",
    companyType: "Startup",
    industry: "Artificial Intelligence",
    bio: "Founder of an AI-powered sales intelligence platform. Series A funded. Hiring ML engineers, full-stack developers, and a product designer.",
    website: "velocityai.com",
    hiringPreference: "Hourly",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.EXPERT,
    commMethod: "Slack",
    availability: "Full-time",
  },
  {
    name: "Catherine Brooks",
    email: "catherine.brooks@skillbridge.dev",
    location: "New York, NY, USA",
    timezone: "America/New_York",
    company: "Brooks & Co Media",
    companyType: "Individual",
    industry: "Media & Publishing",
    bio: "Independent media producer running a popular finance podcast and newsletter. Need a video editor, audio engineer, and web designer.",
    website: "brooksandco.media",
    hiringPreference: "Fixed",
    budgetRange: "Medium",
    preferredExpLevel: ExperienceLevel.MID,
    commMethod: "Email",
    availability: "Part-time",
  },
  {
    name: "Marcus Johnson",
    email: "marcus.johnson@skillbridge.dev",
    location: "Austin, TX, USA",
    timezone: "America/Chicago",
    company: "ShipSwift",
    companyType: "Startup",
    industry: "Logistics",
    bio: "CEO of a YC-backed logistics SaaS company. Looking for senior backend engineers, DevOps specialists, and a data engineer to build our analytics platform.",
    website: "shipswift.io",
    hiringPreference: "Hourly",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.SENIOR,
    commMethod: "Slack",
    availability: "Full-time",
  },
  {
    name: "Laura Bennett",
    email: "laura.bennett@skillbridge.dev",
    location: "Chicago, IL, USA",
    timezone: "America/Chicago",
    company: "Nurture Health",
    companyType: "Startup",
    industry: "Healthcare",
    bio: "Co-founder of a mental health platform connecting therapists with patients. Need HIPAA-compliant mobile apps, backend APIs, and UX research.",
    website: "nurturehealth.com",
    hiringPreference: "Both",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.EXPERT,
    commMethod: "Slack",
    availability: "Full-time",
  },
  {
    name: "Derek Walsh",
    email: "derek.walsh@skillbridge.dev",
    location: "Seattle, WA, USA",
    timezone: "America/Los_Angeles",
    company: "CloudStack Labs",
    companyType: "Enterprise",
    industry: "Cloud Computing",
    bio: "VP of Engineering at a cloud infrastructure company. Hiring DevOps engineers, security specialists, and Go backend developers for a major platform upgrade.",
    website: "cloudstacklabs.com",
    hiringPreference: "Hourly",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.EXPERT,
    commMethod: "Slack",
    availability: "Full-time",
  },
  {
    name: "Sophia Chen",
    email: "sophia.chen@skillbridge.dev",
    location: "Los Angeles, CA, USA",
    timezone: "America/Los_Angeles",
    company: "Luminary Studios",
    companyType: "Startup",
    industry: "Entertainment",
    bio: "Creative director at an independent game studio. Looking for Unity developers, 3D artists, sound designers, and a motion graphic designer.",
    website: "luminarystudios.games",
    hiringPreference: "Fixed",
    budgetRange: "Medium",
    preferredExpLevel: ExperienceLevel.MID,
    commMethod: "Chat",
    availability: "Full-time",
  },
  {
    name: "Brian Foster",
    email: "brian.foster@skillbridge.dev",
    location: "Denver, CO, USA",
    timezone: "America/Denver",
    company: "TrailBlazer Outdoors",
    companyType: "Individual",
    industry: "E-commerce",
    bio: "Owner of an outdoor gear e-commerce brand. Need a Shopify developer, product photographer, email marketing specialist, and SEO writer.",
    website: "trailblazeroutdoors.com",
    hiringPreference: "Fixed",
    budgetRange: "Low",
    preferredExpLevel: ExperienceLevel.ENTRY,
    commMethod: "Email",
    availability: "Part-time",
  },
  {
    name: "Natalie Hughes",
    email: "natalie.hughes@skillbridge.dev",
    location: "Boston, MA, USA",
    timezone: "America/New_York",
    company: "EduForge",
    companyType: "Startup",
    industry: "EdTech",
    bio: "CTO of an adaptive learning platform for K-12 students. Series B funded. Hiring React developers, AI engineers, and a data scientist.",
    website: "eduforge.io",
    hiringPreference: "Hourly",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.EXPERT,
    commMethod: "Slack",
    availability: "Full-time",
  },
  {
    name: "Tyler Morrison",
    email: "tyler.morrison@skillbridge.dev",
    location: "Miami, FL, USA",
    timezone: "America/New_York",
    company: "CryptoVault",
    companyType: "Startup",
    industry: "Web3 / Crypto",
    bio: "Founder of a crypto portfolio management platform. Need Solidity developers, a React frontend engineer, and a blockchain security auditor.",
    website: "cryptovault.finance",
    hiringPreference: "Fixed",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.EXPERT,
    commMethod: "Chat",
    availability: "Full-time",
  },
  {
    name: "Allison Reed",
    email: "allison.reed@skillbridge.dev",
    location: "Portland, OR, USA",
    timezone: "America/Los_Angeles",
    company: "GreenRoot Agency",
    companyType: "Startup",
    industry: "Sustainability",
    bio: "Founder of a sustainability consulting agency. Need a brand identity designer, content writer, and a website developer for our rebrand.",
    website: "greenrootagency.com",
    hiringPreference: "Fixed",
    budgetRange: "Medium",
    preferredExpLevel: ExperienceLevel.MID,
    commMethod: "Email",
    availability: "Part-time",
  },
  {
    name: "Kevin Park",
    email: "kevin.park@skillbridge.dev",
    location: "Dallas, TX, USA",
    timezone: "America/Chicago",
    company: "RetailIQ",
    companyType: "Enterprise",
    industry: "Retail Tech",
    bio: "Director of Product at a retail analytics SaaS company. Looking for data engineers, a BI developer, and a senior React developer.",
    website: "retailiq.com",
    hiringPreference: "Hourly",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.SENIOR,
    commMethod: "Slack",
    availability: "Full-time",
  },
  {
    name: "Hannah Scott",
    email: "hannah.scott@skillbridge.dev",
    location: "Nashville, TN, USA",
    timezone: "America/Chicago",
    company: "SoundWave Records",
    companyType: "Individual",
    industry: "Music",
    bio: "Independent music producer and label owner. Need an audio engineer, a music video editor, album artwork designer, and a digital marketing specialist.",
    website: "soundwaverecords.com",
    hiringPreference: "Fixed",
    budgetRange: "Low",
    preferredExpLevel: ExperienceLevel.MID,
    commMethod: "Chat",
    availability: "Part-time",
  },
  {
    name: "Patrick Evans",
    email: "patrick.evans@skillbridge.dev",
    location: "Phoenix, AZ, USA",
    timezone: "America/Phoenix",
    company: "ConstructIQ",
    companyType: "Enterprise",
    industry: "Construction Tech",
    bio: "CEO of a construction project management SaaS. Looking for mobile developers, backend engineers, and an IoT specialist for site monitoring hardware.",
    website: "constructiq.io",
    hiringPreference: "Both",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.SENIOR,
    commMethod: "Email",
    availability: "Full-time",
  },
  {
    name: "Stephanie Cruz",
    email: "stephanie.cruz@skillbridge.dev",
    location: "San Antonio, TX, USA",
    timezone: "America/Chicago",
    company: "Cruz Digital Marketing",
    companyType: "Individual",
    industry: "Marketing",
    bio: "Freelance marketing consultant running campaigns for local SMBs. Need a graphic designer, SEO writer, and a social media manager.",
    website: "cruzdigital.com",
    hiringPreference: "Fixed",
    budgetRange: "Low",
    preferredExpLevel: ExperienceLevel.ENTRY,
    commMethod: "Chat",
    availability: "Part-time",
  },
  {
    name: "Andrew Phillips",
    email: "andrew.phillips@skillbridge.dev",
    location: "Atlanta, GA, USA",
    timezone: "America/New_York",
    company: "SecureNet Systems",
    companyType: "Enterprise",
    industry: "Cybersecurity",
    bio: "CISO at a managed security services company. Hiring penetration testers, cloud security engineers, and a compliance consultant.",
    website: "securenetsystems.com",
    hiringPreference: "Hourly",
    budgetRange: "High",
    preferredExpLevel: ExperienceLevel.EXPERT,
    commMethod: "Email",
    availability: "Full-time",
  },
];

// ============================================================
// SEED FUNCTION
// ============================================================
export async function seedClients() {
  console.log("🌱 Seeding 25 clients...\n");

  let successCount = 0;
  let skipCount = 0;

  for (const client of CLIENTS) {
    try {
      const passwordHash = await bcrypt.hash("Password@123", 10);

      // 1. Upsert User
      const user = await prisma.user.upsert({
        where: { email: client.email },
        update: {},
        create: {
          name: client.name,
          email: client.email,
          passwordHash,
          role: Role.CLIENT,
          isEmailVerified: true,
          profileImage: `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(client.name)}`,
        },
      });

      // 2. Upsert ClientProfile
      await prisma.clientProfile.upsert({
        where: { userId: user.id },
        update: {
          company: client.company,
          companyType: client.companyType,
          industry: client.industry,
          bio: client.bio,
          website: client.website,
          location: client.location,
          timezone: client.timezone,
          hiringPreference: client.hiringPreference,
          budgetRange: client.budgetRange,
          preferredExpLevel: client.preferredExpLevel,
          commMethod: client.commMethod,
          availability: client.availability,
          profileCompletion: 80,
        },
        create: {
          userId: user.id,
          fullName: client.name,
          company: client.company,
          companyType: client.companyType,
          industry: client.industry,
          bio: client.bio,
          website: client.website,
          location: client.location,
          timezone: client.timezone,
          hiringPreference: client.hiringPreference,
          budgetRange: client.budgetRange,
          preferredExpLevel: client.preferredExpLevel,
          commMethod: client.commMethod,
          availability: client.availability,
          profileCompletion: 80,
        },
      });

      successCount++;
      console.log(`✅ ${client.name} — ${client.company} (${client.location})`);
    } catch (err: any) {
      console.error(`❌ Failed to seed ${client.name}:`, err.message);
      skipCount++;
    }
  }

  console.log("\n────────────────────────────────────────");
  console.log(`✅ Successfully seeded: ${successCount} clients`);
  if (skipCount > 0) console.log(`⚠️  Skipped: ${skipCount}`);
  console.log("────────────────────────────────────────");
  console.log("🔑 All accounts password: Password@123");
}

async function main() {
  await seedClients();
}

if (require.main === module) {
  main()
    .catch((e) => {
      console.error("❌ Seed failed:", e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}