// prisma/seed.ts
import { PrismaClient, ExperienceLevel, AvailabilityStatus, Role } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

// ============================================================
// CATEGORIES (must match your existing seeded categories)
// ============================================================
const CATEGORY_SKILLS: Record<string, string[]> = {
  "web-development": ["React", "Next.js", "TypeScript", "Node.js", "Vue.js", "Angular", "Tailwind CSS", "PostgreSQL", "MongoDB", "GraphQL", "REST API", "PHP", "Laravel", "Django", "Express.js"],
  "mobile-development": ["React Native", "Flutter", "Swift", "Kotlin", "Dart", "Firebase", "Expo", "iOS", "Android", "Redux"],
  "ui-ux-design": ["Figma", "Adobe XD", "Sketch", "Prototyping", "Wireframing", "User Research", "Design Systems", "Framer", "Zeplin", "InVision"],
  "graphic-design": ["Adobe Illustrator", "Adobe Photoshop", "Canva", "Logo Design", "Brand Identity", "Typography", "InDesign", "Procreate", "CorelDRAW", "After Effects"],
  "ai-machine-learning": ["Python", "TensorFlow", "PyTorch", "scikit-learn", "NLP", "Computer Vision", "LangChain", "OpenAI API", "Hugging Face", "MLflow"],
  "data-science": ["Python", "R", "SQL", "Tableau", "Power BI", "Pandas", "NumPy", "Apache Spark", "dbt", "Looker"],
  "devops-cloud": ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD", "GitHub Actions", "Azure", "GCP", "Linux", "Nginx"],
  "cybersecurity": ["Penetration Testing", "Burp Suite", "Metasploit", "OWASP", "Wireshark", "Nmap", "Network Security", "SIEM", "Kali Linux", "ISO 27001"],
  "blockchain-web3": ["Solidity", "Ethereum", "Web3.js", "ethers.js", "Hardhat", "NFT", "DeFi", "Smart Contracts", "IPFS", "Rust"],
  "game-development": ["Unity", "Unreal Engine", "C#", "C++", "Blender", "Game Design", "Godot", "3D Modeling", "Multiplayer", "VR/AR"],
  "software-development": ["Java", "C#", ".NET", "Python", "Go", "Rust", "Microservices", "gRPC", "RabbitMQ", "Redis"],
  "embedded-iot": ["C", "C++", "Arduino", "Raspberry Pi", "MQTT", "Embedded Linux", "RTOS", "PCB Design", "ESP32", "IoT"],
  "writing-content": ["SEO Writing", "Copywriting", "Technical Writing", "Ghost Writing", "Proofreading", "Blog Writing", "UX Writing", "Content Strategy", "Research", "Editing"],
  "digital-marketing": ["SEO", "Google Ads", "Facebook Ads", "Email Marketing", "HubSpot", "Analytics", "Mailchimp", "Ahrefs", "Social Media", "CRO"],
  "video-animation": ["Adobe Premiere Pro", "After Effects", "Final Cut Pro", "DaVinci Resolve", "Motion Graphics", "2D Animation", "3D Animation", "Video Editing", "Color Grading", "VFX"],
  "audio-music": ["Pro Tools", "Logic Pro", "Ableton Live", "Sound Design", "Mixing", "Mastering", "Voice Over", "Podcast Editing", "FL Studio", "Audacity"],
  "3d-ar-vr": ["Blender", "Cinema 4D", "Maya", "3ds Max", "ZBrush", "Unity AR", "ARKit", "ARCore", "Substance Painter", "KeyShot"],
  "business-consulting": ["Business Strategy", "Market Research", "Financial Modeling", "Excel", "PowerPoint", "Project Management", "Agile", "Scrum", "Lean", "Business Plan"],
  "translation-languages": ["English", "Urdu", "Arabic", "French", "Spanish", "German", "Mandarin", "Translation", "Localization", "Subtitling"],
  "admin-virtual-assistance": ["Virtual Assistance", "Data Entry", "Customer Support", "CRM", "Scheduling", "Research", "Shopify", "WordPress", "Email Management", "Lead Generation"],
};

// ============================================================
// FREELANCER DATA
// ============================================================
const FREELANCERS = [
  // ─── PAKISTANI FREELANCERS ───────────────────────────────
  {
    name: "Ali Hassan",
    email: "ali.hassan@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Full-stack React & Node.js developer with 5 years of experience",
    bio: "I build scalable web applications with modern tech stacks. Specialized in React, Node.js, and cloud deployments. Worked with 50+ clients globally.",
    hourlyRate: 35,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/alihassan-dev",
    linkedin: "linkedin.com/in/alihassan",
    categorySlug: "web-development",
    skills: ["React", "Node.js", "TypeScript", "MongoDB", "Tailwind CSS"],
    languages: ["English", "Urdu"],
    responseTime: "within 2 hours",
  },
  {
    name: "Fatima Malik",
    email: "fatima.malik@skillbridge.dev",
    location: "Karachi, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "UI/UX Designer crafting beautiful, user-first digital experiences",
    bio: "Passionate designer with 4+ years creating intuitive interfaces. Proficient in Figma and Design Systems. I turn complex problems into simple, elegant solutions.",
    hourlyRate: 28,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/fatimamalik",
    portfolio: "fatimamalik.design",
    categorySlug: "ui-ux-design",
    skills: ["Figma", "Adobe XD", "Prototyping", "Wireframing", "Design Systems"],
    languages: ["English", "Urdu"],
    responseTime: "within 4 hours",
  },
  {
    name: "Usman Tariq",
    email: "usman.tariq@skillbridge.dev",
    location: "Islamabad, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "DevOps Engineer | AWS Certified | Kubernetes & CI/CD Expert",
    bio: "AWS certified DevOps engineer with expertise in containerization, infrastructure as code, and building bulletproof CI/CD pipelines for startups and enterprises.",
    hourlyRate: 40,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/usmantariq",
    linkedin: "linkedin.com/in/usmantariq",
    categorySlug: "devops-cloud",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"],
    languages: ["English", "Urdu"],
    responseTime: "within 3 hours",
  },
  {
    name: "Ayesha Siddiqui",
    email: "ayesha.siddiqui@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "AI/ML Engineer | Python | Deep Learning | LLM Integration",
    bio: "Machine learning engineer specializing in NLP and computer vision. Built production-grade ML pipelines for e-commerce, fintech, and healthcare clients.",
    hourlyRate: 45,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/ayeshasiddiqui-ml",
    linkedin: "linkedin.com/in/ayeshasiddiqui",
    categorySlug: "ai-machine-learning",
    skills: ["Python", "TensorFlow", "PyTorch", "NLP", "OpenAI API"],
    languages: ["English", "Urdu"],
    responseTime: "within 6 hours",
  },
  {
    name: "Bilal Ahmed",
    email: "bilal.ahmed@skillbridge.dev",
    location: "Faisalabad, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Mobile App Developer | React Native & Flutter | 4 Years",
    bio: "Cross-platform mobile developer who has shipped 20+ apps to the App Store and Play Store. Focused on performance, offline-first architecture, and smooth animations.",
    hourlyRate: 30,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/bilalahmed-mobile",
    categorySlug: "mobile-development",
    skills: ["React Native", "Flutter", "Firebase", "Redux", "Expo"],
    languages: ["English", "Urdu"],
    responseTime: "within 2 hours",
  },
  {
    name: "Zainab Raza",
    email: "zainab.raza@skillbridge.dev",
    location: "Karachi, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Blockchain Developer | Solidity | DeFi | Smart Contracts",
    bio: "Web3 developer with 3 years building DeFi protocols, NFT marketplaces, and DAO tooling on Ethereum and Polygon. Audited 10+ smart contracts.",
    hourlyRate: 50,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.BUSY,
    github: "github.com/zainabraza-web3",
    linkedin: "linkedin.com/in/zainabraza",
    categorySlug: "blockchain-web3",
    skills: ["Solidity", "Ethereum", "ethers.js", "Hardhat", "DeFi"],
    languages: ["English", "Urdu"],
    responseTime: "within 8 hours",
  },
  {
    name: "Hamza Khan",
    email: "hamza.khan@skillbridge.dev",
    location: "Peshawar, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Data Scientist | Python | Power BI | Business Intelligence",
    bio: "Data scientist with 5 years turning messy datasets into actionable insights. Expert in building dashboards, forecasting models, and ETL pipelines.",
    hourlyRate: 32,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/hamzakhan-data",
    linkedin: "linkedin.com/in/hamzakhan",
    categorySlug: "data-science",
    skills: ["Python", "SQL", "Power BI", "Pandas", "Apache Spark"],
    languages: ["English", "Urdu", "Pashto"],
    responseTime: "within 4 hours",
  },
  {
    name: "Sana Butt",
    email: "sana.butt@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Graphic Designer | Brand Identity | Logo Design | 6 Years",
    bio: "Creative graphic designer specializing in brand identity, logo design, and print materials. Have worked with 100+ brands from startups to Fortune 500 companies.",
    hourlyRate: 22,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "sanabutt.design",
    linkedin: "linkedin.com/in/sanabutt",
    categorySlug: "graphic-design",
    skills: ["Adobe Illustrator", "Adobe Photoshop", "Logo Design", "Brand Identity", "Typography"],
    languages: ["English", "Urdu"],
    responseTime: "within 3 hours",
  },
  {
    name: "Tariq Mehmood",
    email: "tariq.mehmood@skillbridge.dev",
    location: "Multan, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Cybersecurity Specialist | Pen Testing | OWASP | CEH Certified",
    bio: "Certified Ethical Hacker with expertise in web application security, network penetration testing, and vulnerability assessments. Secured 30+ applications.",
    hourlyRate: 55,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/tariqmehmood-security",
    categorySlug: "cybersecurity",
    skills: ["Penetration Testing", "Burp Suite", "OWASP", "Kali Linux", "Network Security"],
    languages: ["English", "Urdu"],
    responseTime: "within 5 hours",
  },
  {
    name: "Nadia Iqbal",
    email: "nadia.iqbal@skillbridge.dev",
    location: "Rawalpindi, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Content Writer & SEO Specialist | Tech & SaaS Niche",
    bio: "Technical content writer with 4 years creating SEO-optimized blog posts, documentation, and whitepapers for SaaS and tech companies. 200+ published articles.",
    hourlyRate: 18,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/nadiaiqbal",
    portfolio: "nadiaiqbal.com",
    categorySlug: "writing-content",
    skills: ["SEO Writing", "Technical Writing", "Blog Writing", "Copywriting", "Research"],
    languages: ["English", "Urdu"],
    responseTime: "within 2 hours",
  },
  {
    name: "Asad Javed",
    email: "asad.javed@skillbridge.dev",
    location: "Karachi, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Unity Game Developer | 3D Games | Multiplayer Systems",
    bio: "Game developer with 5 years building mobile and PC games in Unity. Shipped 8 games with 1M+ combined downloads. Specialized in multiplayer and real-time systems.",
    hourlyRate: 38,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/asadjaved-games",
    categorySlug: "game-development",
    skills: ["Unity", "C#", "Multiplayer", "Game Design", "3D Modeling"],
    languages: ["English", "Urdu"],
    responseTime: "within 4 hours",
  },
  {
    name: "Maira Shahid",
    email: "maira.shahid@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Virtual Assistant | Admin Support | CRM & Scheduling Expert",
    bio: "Experienced virtual assistant helping busy entrepreneurs and executives manage their operations, calendars, emails, and CRM systems efficiently.",
    hourlyRate: 12,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/maira-shahid",
    categorySlug: "admin-virtual-assistance",
    skills: ["Virtual Assistance", "CRM", "Scheduling", "Email Management", "Data Entry"],
    languages: ["English", "Urdu"],
    responseTime: "within 1 hour",
  },
  {
    name: "Kamran Hussain",
    email: "kamran.hussain@skillbridge.dev",
    location: "Islamabad, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Embedded Systems & IoT Developer | C/C++ | Arduino | ESP32",
    bio: "Embedded engineer building IoT solutions for industrial automation, smart home, and agriculture. Experienced in both hardware interfacing and firmware development.",
    hourlyRate: 35,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/kamranhussain-iot",
    categorySlug: "embedded-iot",
    skills: ["C", "C++", "Arduino", "ESP32", "MQTT"],
    languages: ["English", "Urdu"],
    responseTime: "within 6 hours",
  },
  {
    name: "Sara Nawaz",
    email: "sara.nawaz@skillbridge.dev",
    location: "Karachi, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "3D Artist & Visualizer | Blender | Architectural Visualization",
    bio: "3D artist specializing in photorealistic architectural visualization and product rendering. Worked with real estate agencies, architects, and product brands.",
    hourlyRate: 26,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "saranawaz3d.com",
    categorySlug: "3d-ar-vr",
    skills: ["Blender", "Cinema 4D", "KeyShot", "Substance Painter", "3D Modeling"],
    languages: ["English", "Urdu"],
    responseTime: "within 5 hours",
  },
  {
    name: "Faisal Rehman",
    email: "faisal.rehman@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Digital Marketing Expert | SEO | Google Ads | Growth Hacking",
    bio: "Growth-focused digital marketer helping SaaS and e-commerce brands scale. Managed $500K+ in ad spend with consistent 4x+ ROAS. Google and Meta certified.",
    hourlyRate: 30,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/faisalrehman-marketing",
    categorySlug: "digital-marketing",
    skills: ["SEO", "Google Ads", "Facebook Ads", "Analytics", "CRO"],
    languages: ["English", "Urdu"],
    responseTime: "within 3 hours",
  },
  {
    name: "Hira Zahid",
    email: "hira.zahid@skillbridge.dev",
    location: "Rawalpindi, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Translator | English ↔ Urdu | Arabic | Legal & Tech Documents",
    bio: "Professional translator with 6 years translating legal, technical, and marketing content between English, Urdu, and Arabic. ISO 17100 compliant workflow.",
    hourlyRate: 16,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/hirazahid-translator",
    categorySlug: "translation-languages",
    skills: ["English", "Urdu", "Arabic", "Translation", "Localization"],
    languages: ["English", "Urdu", "Arabic"],
    responseTime: "within 4 hours",
  },
  {
    name: "Omar Farooq",
    email: "omar.farooq@skillbridge.dev",
    location: "Faisalabad, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Video Editor & Motion Designer | YouTube | Ads | Reels",
    bio: "Video editor and motion designer with 5 years creating engaging content for YouTube channels, product ads, and social media. 50M+ combined views on edited content.",
    hourlyRate: 20,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "omarfarooq.video",
    categorySlug: "video-animation",
    skills: ["Adobe Premiere Pro", "After Effects", "Motion Graphics", "Color Grading", "Video Editing"],
    languages: ["English", "Urdu"],
    responseTime: "within 3 hours",
  },
  {
    name: "Rabia Qureshi",
    email: "rabia.qureshi@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Business Consultant | Startup Strategy | Market Research | MBA",
    bio: "MBA-qualified business consultant helping early-stage startups with go-to-market strategy, pitch decks, and financial modeling. Advised 25+ funded startups.",
    hourlyRate: 45,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/rabiaqureshi-consulting",
    categorySlug: "business-consulting",
    skills: ["Business Strategy", "Market Research", "Financial Modeling", "Agile", "Business Plan"],
    languages: ["English", "Urdu"],
    responseTime: "within 6 hours",
  },
  {
    name: "Waqas Ali",
    email: "waqas.ali@skillbridge.dev",
    location: "Karachi, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Backend Java Developer | Spring Boot | Microservices | 6 Years",
    bio: "Senior Java developer building enterprise-grade microservices and APIs. Experienced with Spring Boot, Kafka, and distributed systems at scale.",
    hourlyRate: 42,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/waqasali-java",
    linkedin: "linkedin.com/in/waqasali",
    categorySlug: "software-development",
    skills: ["Java", "C#", "Microservices", "gRPC", "Redis"],
    languages: ["English", "Urdu"],
    responseTime: "within 4 hours",
  },
  {
    name: "Mehwish Baig",
    email: "mehwish.baig@skillbridge.dev",
    location: "Islamabad, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Audio Producer & Sound Designer | Podcasts | Jingles | VO",
    bio: "Professional audio producer with 4 years creating podcast episodes, brand jingles, and voice-over productions for clients across North America and the Middle East.",
    hourlyRate: 22,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "mehwishbaig.audio",
    categorySlug: "audio-music",
    skills: ["Logic Pro", "Ableton Live", "Sound Design", "Podcast Editing", "Mixing"],
    languages: ["English", "Urdu"],
    responseTime: "within 5 hours",
  },

  // --- 30 more Pakistani freelancers ---
  {
    name: "Zubair Malik",
    email: "zubair.malik@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Next.js & TypeScript Expert | SaaS Products | API Design",
    bio: "Frontend-leaning full-stack developer building fast, SEO-friendly SaaS apps with Next.js. Passionate about clean code, performance, and developer experience.",
    hourlyRate: 38,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/zubairmalik",
    categorySlug: "web-development",
    skills: ["Next.js", "TypeScript", "React", "GraphQL", "PostgreSQL"],
    languages: ["English", "Urdu"],
    responseTime: "within 2 hours",
  },
  {
    name: "Amna Farhan",
    email: "amna.farhan@skillbridge.dev",
    location: "Karachi, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Flutter Developer | Cross-Platform Apps | Firebase | BLoC",
    bio: "Flutter developer with expertise in building beautiful cross-platform apps. Delivered apps for fintech, e-commerce, and healthcare verticals.",
    hourlyRate: 28,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/amnafarhan-flutter",
    categorySlug: "mobile-development",
    skills: ["Flutter", "Dart", "Firebase", "React Native", "Redux"],
    languages: ["English", "Urdu"],
    responseTime: "within 3 hours",
  },
  {
    name: "Junaid Bashir",
    email: "junaid.bashir@skillbridge.dev",
    location: "Multan, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Data Analyst | SQL | Tableau | Excel Dashboards",
    bio: "Business data analyst helping companies visualize their KPIs and make data-driven decisions. Expert in SQL querying, Tableau dashboards, and financial reporting.",
    hourlyRate: 24,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/junaidbashir",
    categorySlug: "data-science",
    skills: ["SQL", "Tableau", "Python", "Power BI", "NumPy"],
    languages: ["English", "Urdu"],
    responseTime: "within 4 hours",
  },
  {
    name: "Lubna Saeed",
    email: "lubna.saeed@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "UX Researcher | Usability Testing | User Interviews | Figma",
    bio: "UX researcher focused on discovering user needs through qualitative and quantitative research. Helped 15+ product teams reduce churn through better onboarding flows.",
    hourlyRate: 30,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "lubnasaeed.ux",
    categorySlug: "ui-ux-design",
    skills: ["User Research", "Figma", "Prototyping", "Wireframing", "Usability Testing"],
    languages: ["English", "Urdu"],
    responseTime: "within 5 hours",
  },
  {
    name: "Hassan Rauf",
    email: "hassan.rauf@skillbridge.dev",
    location: "Peshawar, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Solidity & Rust Developer | Blockchain Infrastructure",
    bio: "Blockchain infrastructure developer with deep expertise in Solidity, Rust-based chains, and Layer 2 solutions. Contributed to 3 open-source DeFi protocols.",
    hourlyRate: 55,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.BUSY,
    github: "github.com/hassanrauf-web3",
    categorySlug: "blockchain-web3",
    skills: ["Solidity", "Rust", "Smart Contracts", "IPFS", "Web3.js"],
    languages: ["English", "Urdu", "Pashto"],
    responseTime: "within 12 hours",
  },
  {
    name: "Tooba Anwar",
    email: "tooba.anwar@skillbridge.dev",
    location: "Karachi, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Brand Identity Designer | Packaging | Print & Digital",
    bio: "Visual identity designer with a keen eye for typography and color. Built brand identities for 80+ businesses ranging from local restaurants to international e-commerce brands.",
    hourlyRate: 25,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "toobaanwar.design",
    categorySlug: "graphic-design",
    skills: ["Adobe Illustrator", "InDesign", "Brand Identity", "Packaging Design", "Typography"],
    languages: ["English", "Urdu"],
    responseTime: "within 3 hours",
  },
  {
    name: "Shahbaz Gondal",
    email: "shahbaz.gondal@skillbridge.dev",
    location: "Gujranwala, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "AWS Solutions Architect | Cloud Migration | Serverless",
    bio: "AWS certified Solutions Architect with 6 years of experience migrating monolith applications to cloud-native serverless architectures. Cut infra costs by 40% on avg.",
    hourlyRate: 50,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/shahbazgondal",
    categorySlug: "devops-cloud",
    skills: ["AWS", "Terraform", "Docker", "GitHub Actions", "Linux"],
    languages: ["English", "Urdu"],
    responseTime: "within 4 hours",
  },
  {
    name: "Aisha Nisar",
    email: "aisha.nisar@skillbridge.dev",
    location: "Islamabad, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "SEO Content Strategist | SaaS | B2B | Long-form Writing",
    bio: "Content strategist and writer helping B2B SaaS brands rank on Google and generate leads through well-researched, deeply strategic content.",
    hourlyRate: 20,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "aishanisar.com",
    categorySlug: "writing-content",
    skills: ["SEO Writing", "Content Strategy", "Blog Writing", "Copywriting", "UX Writing"],
    languages: ["English", "Urdu"],
    responseTime: "within 2 hours",
  },
  {
    name: "Khurram Shahzad",
    email: "khurram.shahzad@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Unreal Engine 5 Developer | AAA-Quality Games | VR",
    bio: "Unreal Engine 5 developer creating high-fidelity games and interactive VR experiences. Worked on architectural visualization and training simulations.",
    hourlyRate: 45,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/khurramshahzad-ue5",
    categorySlug: "game-development",
    skills: ["Unreal Engine", "C++", "VR/AR", "3D Modeling", "Game Design"],
    languages: ["English", "Urdu"],
    responseTime: "within 6 hours",
  },
  {
    name: "Rida Zafar",
    email: "rida.zafar@skillbridge.dev",
    location: "Karachi, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Python ML Engineer | Computer Vision | OpenCV | YOLO",
    bio: "ML engineer specializing in real-time computer vision systems for surveillance, quality control, and autonomous navigation. Deployed models on edge devices.",
    hourlyRate: 42,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/ridazafar-cv",
    categorySlug: "ai-machine-learning",
    skills: ["Python", "Computer Vision", "PyTorch", "scikit-learn", "Hugging Face"],
    languages: ["English", "Urdu"],
    responseTime: "within 5 hours",
  },
  {
    name: "Naveed Akhtar",
    email: "naveed.akhtar@skillbridge.dev",
    location: "Quetta, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "IoT & Embedded Linux Developer | Smart Agriculture & Industry",
    bio: "Embedded Linux developer building IoT solutions for smart agriculture and industrial monitoring. Expert in MQTT, sensor integration, and cloud connectivity.",
    hourlyRate: 30,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/naveedakhtar-iot",
    categorySlug: "embedded-iot",
    skills: ["Embedded Linux", "C", "MQTT", "Raspberry Pi", "IoT"],
    languages: ["English", "Urdu", "Balochi"],
    responseTime: "within 8 hours",
  },
  {
    name: "Maryam Ghani",
    email: "maryam.ghani@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "3D Animator | Blender | Character Design | Product Visualization",
    bio: "3D animator and character designer creating compelling animations for games, explainer videos, and product showcases. Blender specialist with Cinema 4D experience.",
    hourlyRate: 28,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "maryamghani3d.com",
    categorySlug: "3d-ar-vr",
    skills: ["Blender", "Maya", "3D Modeling", "ZBrush", "Cinema 4D"],
    languages: ["English", "Urdu"],
    responseTime: "within 4 hours",
  },
  {
    name: "Shoaib Mirza",
    email: "shoaib.mirza@skillbridge.dev",
    location: "Hyderabad, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Email Marketing Specialist | Klaviyo | HubSpot | Automation",
    bio: "Email marketing specialist with a proven track record of increasing open rates and revenue for e-commerce brands through personalized automation flows.",
    hourlyRate: 22,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/shoaibmirza",
    categorySlug: "digital-marketing",
    skills: ["Email Marketing", "HubSpot", "Mailchimp", "Analytics", "Social Media"],
    languages: ["English", "Urdu", "Sindhi"],
    responseTime: "within 3 hours",
  },
  {
    name: "Anum Shafiq",
    email: "anum.shafiq@skillbridge.dev",
    location: "Lahore, Pakistan",
    timezone: "Asia/Karachi",
    tagline: "Document Translator | English ↔ Urdu | Legal | Medical",
    bio: "Certified translator specializing in legal, medical, and financial document translation between English and Urdu. Quick turnaround with 99% accuracy rate.",
    hourlyRate: 14,
    experienceLevel: ExperienceLevel.MID,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/anumshafiq",
    categorySlug: "translation-languages",
    skills: ["English", "Urdu", "Translation", "Subtitling", "Localization"],
    languages: ["English", "Urdu"],
    responseTime: "within 2 hours",
  },
  {
    name: "Adeel Sultan",
    email: "adeel.sultan@skillbridge.dev",
    location: "Rawalpindi, Pakistan",
    timezone: "Asia/Karachi",
    tagline: ".NET & C# Developer | Enterprise Software | Azure",
    bio: "Enterprise .NET developer with 7 years of experience building ERP systems, internal tools, and customer-facing portals. Microsoft Azure certified.",
    hourlyRate: 40,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/adeelsultan-dotnet",
    linkedin: "linkedin.com/in/adeelsultan",
    categorySlug: "software-development",
    skills: [".NET", "C#", "Java", "Microservices", "Redis"],
    languages: ["English", "Urdu"],
    responseTime: "within 4 hours",
  },

  // ─── AMERICAN FREELANCERS ───────────────────────────────
  {
    name: "James Carter",
    email: "james.carter@skillbridge.dev",
    location: "San Francisco, CA, USA",
    timezone: "America/Los_Angeles",
    tagline: "Senior React Developer | Design Systems | Web Performance",
    bio: "10 years of frontend engineering experience at startups and FAANG. Passionate about component architecture, accessibility, and core web vitals.",
    hourlyRate: 120,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/jamescarter-dev",
    linkedin: "linkedin.com/in/jamescarter",
    categorySlug: "web-development",
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Tailwind CSS"],
    languages: ["English"],
    responseTime: "within 4 hours",
  },
  {
    name: "Emily Rodriguez",
    email: "emily.rodriguez@skillbridge.dev",
    location: "New York, NY, USA",
    timezone: "America/New_York",
    tagline: "Product Designer | UX Strategy | B2B SaaS | Figma",
    bio: "Product designer with 8 years shaping digital products at Series A to Series C startups. Obsessed with reducing friction in complex enterprise workflows.",
    hourlyRate: 110,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "emilyrodriguez.design",
    linkedin: "linkedin.com/in/emilyrodriguez",
    categorySlug: "ui-ux-design",
    skills: ["Figma", "Design Systems", "User Research", "Prototyping", "UX Writing"],
    languages: ["English", "Spanish"],
    responseTime: "within 3 hours",
  },
  {
    name: "Michael Thompson",
    email: "michael.thompson@skillbridge.dev",
    location: "Austin, TX, USA",
    timezone: "America/Chicago",
    tagline: "AI/ML Engineer | LLMs | RAG | Python | Production ML",
    bio: "Machine learning engineer with a background in NLP and LLM fine-tuning. Built RAG pipelines and AI-powered features for Series B startups and enterprise clients.",
    hourlyRate: 130,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/michaelthompson-ml",
    linkedin: "linkedin.com/in/michaelthompson",
    categorySlug: "ai-machine-learning",
    skills: ["Python", "LangChain", "OpenAI API", "PyTorch", "Hugging Face"],
    languages: ["English"],
    responseTime: "within 5 hours",
  },
  {
    name: "Sarah Johnson",
    email: "sarah.johnson@skillbridge.dev",
    location: "Seattle, WA, USA",
    timezone: "America/Los_Angeles",
    tagline: "Cloud Architect | AWS | Kubernetes | Platform Engineering",
    bio: "Platform engineer and AWS solutions architect with 9 years building resilient, cost-efficient cloud infrastructure for fintech and e-commerce at scale.",
    hourlyRate: 140,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.BUSY,
    linkedin: "linkedin.com/in/sarahjohnson-cloud",
    categorySlug: "devops-cloud",
    skills: ["AWS", "Kubernetes", "Terraform", "CI/CD", "GCP"],
    languages: ["English"],
    responseTime: "within 6 hours",
  },
  {
    name: "David Kim",
    email: "david.kim@skillbridge.dev",
    location: "Los Angeles, CA, USA",
    timezone: "America/Los_Angeles",
    tagline: "iOS & Swift Developer | 7 Years | App Store Top Charts",
    bio: "iOS developer who has shipped 12 apps with over 5M combined downloads. Expert in SwiftUI, Core Data, and integrating complex third-party SDKs.",
    hourlyRate: 115,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/davidkim-ios",
    linkedin: "linkedin.com/in/davidkim",
    categorySlug: "mobile-development",
    skills: ["Swift", "iOS", "React Native", "Firebase", "Redux"],
    languages: ["English", "Korean"],
    responseTime: "within 4 hours",
  },
  {
    name: "Jessica Williams",
    email: "jessica.williams@skillbridge.dev",
    location: "Chicago, IL, USA",
    timezone: "America/Chicago",
    tagline: "Blockchain Security Auditor | Solidity | DeFi | Smart Contracts",
    bio: "Smart contract security researcher and auditor. Discovered critical vulnerabilities in 20+ DeFi protocols. Contributor to Ethereum security tooling.",
    hourlyRate: 160,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/jessicawilliams-audit",
    categorySlug: "blockchain-web3",
    skills: ["Solidity", "Smart Contracts", "DeFi", "Ethereum", "Web3.js"],
    languages: ["English"],
    responseTime: "within 8 hours",
  },
  {
    name: "Robert Davis",
    email: "robert.davis@skillbridge.dev",
    location: "Boston, MA, USA",
    timezone: "America/New_York",
    tagline: "Cybersecurity Consultant | CISSP | Red Team | Zero Trust",
    bio: "CISSP-certified cybersecurity consultant with 12 years conducting red team exercises, security architecture reviews, and incident response for Fortune 500 companies.",
    hourlyRate: 175,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/robertdavis-security",
    categorySlug: "cybersecurity",
    skills: ["Penetration Testing", "Network Security", "OWASP", "Metasploit", "ISO 27001"],
    languages: ["English"],
    responseTime: "within 6 hours",
  },
  {
    name: "Amanda Clark",
    email: "amanda.clark@skillbridge.dev",
    location: "Denver, CO, USA",
    timezone: "America/Denver",
    tagline: "Brand Strategist & Designer | Identity | Packaging | Campaigns",
    bio: "Brand strategist and senior designer who has built visual identities for venture-backed startups and household CPG brands. Strong in strategy, design, and storytelling.",
    hourlyRate: 95,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "amandaclark.studio",
    linkedin: "linkedin.com/in/amandaclark",
    categorySlug: "graphic-design",
    skills: ["Adobe Illustrator", "Adobe Photoshop", "Brand Identity", "Logo Design", "Packaging Design"],
    languages: ["English"],
    responseTime: "within 5 hours",
  },
  {
    name: "Christopher Lee",
    email: "christopher.lee@skillbridge.dev",
    location: "San Diego, CA, USA",
    timezone: "America/Los_Angeles",
    tagline: "Data Engineer | Spark | dbt | Snowflake | ELT Pipelines",
    bio: "Data engineer specializing in building modern data stacks with Spark, dbt, and Snowflake. Helped 10+ companies migrate from legacy warehouses to cloud-native solutions.",
    hourlyRate: 125,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/christopherlee-data",
    linkedin: "linkedin.com/in/christopherlee",
    categorySlug: "data-science",
    skills: ["Python", "Apache Spark", "SQL", "dbt", "Tableau"],
    languages: ["English"],
    responseTime: "within 4 hours",
  },
  {
    name: "Megan White",
    email: "megan.white@skillbridge.dev",
    location: "Portland, OR, USA",
    timezone: "America/Los_Angeles",
    tagline: "Technical Writer | API Docs | Developer Experience | Markdown",
    bio: "Technical writer specializing in developer documentation, API references, and SDK guides for developer-first startups. Advocate for docs-as-code workflows.",
    hourlyRate: 80,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "meganwhite.dev",
    linkedin: "linkedin.com/in/meganwhite",
    categorySlug: "writing-content",
    skills: ["Technical Writing", "SEO Writing", "UX Writing", "Copywriting", "Research"],
    languages: ["English"],
    responseTime: "within 3 hours",
  },
  {
    name: "Daniel Martinez",
    email: "daniel.martinez@skillbridge.dev",
    location: "Miami, FL, USA",
    timezone: "America/New_York",
    tagline: "Unity & Unreal Game Developer | VR/AR | Simulations",
    bio: "Game and simulation developer with 8 years building games and enterprise VR training simulations. Led teams at two AA studios and shipped 6 commercial titles.",
    hourlyRate: 110,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/danielmartinez-games",
    categorySlug: "game-development",
    skills: ["Unity", "Unreal Engine", "C#", "C++", "VR/AR"],
    languages: ["English", "Spanish"],
    responseTime: "within 5 hours",
  },
  {
    name: "Lauren Taylor",
    email: "lauren.taylor@skillbridge.dev",
    location: "Nashville, TN, USA",
    timezone: "America/Chicago",
    tagline: "Music Producer & Audio Engineer | Film Scoring | Podcasts",
    bio: "Grammy-nominated audio engineer and music producer. Specializes in podcast production, film scoring, and brand audio identities for tech companies.",
    hourlyRate: 90,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "laurentaylor.audio",
    categorySlug: "audio-music",
    skills: ["Pro Tools", "Logic Pro", "Mixing", "Mastering", "Sound Design"],
    languages: ["English"],
    responseTime: "within 6 hours",
  },
  {
    name: "Kevin Anderson",
    email: "kevin.anderson@skillbridge.dev",
    location: "Phoenix, AZ, USA",
    timezone: "America/Phoenix",
    tagline: "Video Director & Editor | Commercials | YouTube | Documentary",
    bio: "Filmmaker and video director with 10 years producing commercials, YouTube content, and brand documentaries. Clients include Fortune 500 brands and viral creators.",
    hourlyRate: 100,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "kevinanderson.film",
    categorySlug: "video-animation",
    skills: ["Adobe Premiere Pro", "After Effects", "DaVinci Resolve", "Video Editing", "VFX"],
    languages: ["English"],
    responseTime: "within 4 hours",
  },
  {
    name: "Rachel Green",
    email: "rachel.green@skillbridge.dev",
    location: "Atlanta, GA, USA",
    timezone: "America/New_York",
    tagline: "Growth Marketer | SEO | Content Strategy | HubSpot Partner",
    bio: "Growth marketer and HubSpot certified partner helping B2B SaaS companies build inbound engines. Grew organic traffic by 10x for 5 different companies.",
    hourlyRate: 85,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/rachelgreen-marketing",
    categorySlug: "digital-marketing",
    skills: ["SEO", "HubSpot", "Content Marketing", "Email Marketing", "Analytics"],
    languages: ["English"],
    responseTime: "within 3 hours",
  },
  {
    name: "Brandon Wilson",
    email: "brandon.wilson@skillbridge.dev",
    location: "Dallas, TX, USA",
    timezone: "America/Chicago",
    tagline: "Go & Rust Backend Developer | High-Performance Systems",
    bio: "Systems programmer specializing in high-throughput backend services in Go and Rust. Built payment processing systems handling 100K+ transactions per second.",
    hourlyRate: 135,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/brandonwilson-systems",
    linkedin: "linkedin.com/in/brandonwilson",
    categorySlug: "software-development",
    skills: ["Go", "Rust", "Microservices", "gRPC", "RabbitMQ"],
    languages: ["English"],
    responseTime: "within 4 hours",
  },
  {
    name: "Stephanie Moore",
    email: "stephanie.moore@skillbridge.dev",
    location: "Minneapolis, MN, USA",
    timezone: "America/Chicago",
    tagline: "Business Consultant | M&A | Financial Modeling | Strategy",
    bio: "Former McKinsey consultant specializing in growth strategy, M&A due diligence, and operational efficiency for mid-market and enterprise clients.",
    hourlyRate: 200,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/stephaniemoore-consulting",
    categorySlug: "business-consulting",
    skills: ["Business Strategy", "Financial Modeling", "Market Research", "Excel", "PowerPoint"],
    languages: ["English"],
    responseTime: "within 8 hours",
  },
  {
    name: "Tyler Jackson",
    email: "tyler.jackson@skillbridge.dev",
    location: "Salt Lake City, UT, USA",
    timezone: "America/Denver",
    tagline: "AR/VR Developer | Unity | WebXR | Meta Quest | HoloLens",
    bio: "Extended reality developer building immersive training, retail, and entertainment experiences for Meta Quest, HoloLens, and WebXR platforms.",
    hourlyRate: 120,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/tylerjackson-xr",
    categorySlug: "3d-ar-vr",
    skills: ["Unity AR", "ARKit", "ARCore", "Blender", "3D Modeling"],
    languages: ["English"],
    responseTime: "within 5 hours",
  },
  {
    name: "Nicole Harris",
    email: "nicole.harris@skillbridge.dev",
    location: "Philadelphia, PA, USA",
    timezone: "America/New_York",
    tagline: "Executive Virtual Assistant | C-Suite Support | Operations",
    bio: "High-touch executive assistant with 8 years supporting C-suite leaders at Series B startups. Expert in managing complex calendars, travel, and special projects.",
    hourlyRate: 55,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/nicoleharris-va",
    categorySlug: "admin-virtual-assistance",
    skills: ["Virtual Assistance", "Scheduling", "CRM", "Research", "Email Management"],
    languages: ["English"],
    responseTime: "within 1 hour",
  },
  {
    name: "Andrew Walker",
    email: "andrew.walker@skillbridge.dev",
    location: "Houston, TX, USA",
    timezone: "America/Chicago",
    tagline: "Embedded Systems Engineer | RTOS | Automotive | Aerospace",
    bio: "Embedded software engineer with 10 years in automotive and aerospace industries. Expert in RTOS, CAN bus, and safety-critical embedded C development (ISO 26262).",
    hourlyRate: 145,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/andrewwalker-embedded",
    linkedin: "linkedin.com/in/andrewwalker",
    categorySlug: "embedded-iot",
    skills: ["C", "C++", "RTOS", "Embedded Linux", "PCB Design"],
    languages: ["English"],
    responseTime: "within 6 hours",
  },
  {
    name: "Samantha Brown",
    email: "samantha.brown@skillbridge.dev",
    location: "Washington, DC, USA",
    timezone: "America/New_York",
    tagline: "Spanish & French Translator | Legal | Government | Certified",
    bio: "ATA-certified translator specializing in legal, government, and healthcare documents. 10+ years providing high-accuracy translations for federal agencies and law firms.",
    hourlyRate: 70,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/samanthabrown-translator",
    categorySlug: "translation-languages",
    skills: ["English", "Spanish", "French", "Translation", "Legal Translation"],
    languages: ["English", "Spanish", "French"],
    responseTime: "within 4 hours",
  },

  // --- 30 more Americans ---
  {
    name: "Ryan Cooper",
    email: "ryan.cooper@skillbridge.dev",
    location: "San Jose, CA, USA",
    timezone: "America/Los_Angeles",
    tagline: "Backend Python Developer | FastAPI | Django | PostgreSQL",
    bio: "Backend engineer with 6 years building REST and GraphQL APIs in Python. Contributed to open-source projects with 10K+ GitHub stars.",
    hourlyRate: 115,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/ryancooper-python",
    categorySlug: "web-development",
    skills: ["Python", "Django", "REST API", "PostgreSQL", "MongoDB"],
    languages: ["English"],
    responseTime: "within 3 hours",
  },
  {
    name: "Ashley Turner",
    email: "ashley.turner@skillbridge.dev",
    location: "Raleigh, NC, USA",
    timezone: "America/New_York",
    tagline: "Android & Kotlin Developer | Material Design | MVVM",
    bio: "Android developer specializing in Kotlin and Jetpack Compose. Shipped 8 apps to Play Store including a fintech app with 500K+ active users.",
    hourlyRate: 100,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/ashleyturner-android",
    categorySlug: "mobile-development",
    skills: ["Kotlin", "Android", "React Native", "Firebase", "Expo"],
    languages: ["English"],
    responseTime: "within 4 hours",
  },
  {
    name: "Joshua Hall",
    email: "joshua.hall@skillbridge.dev",
    location: "Columbus, OH, USA",
    timezone: "America/New_York",
    tagline: "Data Scientist | NLP | Financial Analytics | Python | R",
    bio: "Data scientist with 7 years in financial services and healthtech. Expert in NLP for document classification and predictive modeling for risk assessment.",
    hourlyRate: 120,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/joshuahall-data",
    linkedin: "linkedin.com/in/joshuahall",
    categorySlug: "data-science",
    skills: ["Python", "R", "SQL", "Pandas", "Looker"],
    languages: ["English"],
    responseTime: "within 5 hours",
  },
  {
    name: "Brittany Allen",
    email: "brittany.allen@skillbridge.dev",
    location: "San Antonio, TX, USA",
    timezone: "America/Chicago",
    tagline: "UX/UI Designer | Mobile-First | E-commerce | Shopify",
    bio: "Mobile-first UX designer with 6 years improving conversion rates for e-commerce brands. Reduced cart abandonment by 35% for a $50M DTC brand.",
    hourlyRate: 90,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "brittanyallen.ux",
    categorySlug: "ui-ux-design",
    skills: ["Figma", "Sketch", "Mobile UI/UX", "Wireframing", "Prototyping"],
    languages: ["English"],
    responseTime: "within 3 hours",
  },
  {
    name: "Nathan Scott",
    email: "nathan.scott@skillbridge.dev",
    location: "Charlotte, NC, USA",
    timezone: "America/New_York",
    tagline: "Ethereum & Layer 2 Developer | Optimism | zkSync | DeFi",
    bio: "Ethereum developer focused on Layer 2 scaling solutions. Deployed contracts on Optimism, Arbitrum, and zkSync. Built a DEX aggregator processing $10M daily volume.",
    hourlyRate: 150,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.BUSY,
    github: "github.com/nathanscott-defi",
    categorySlug: "blockchain-web3",
    skills: ["Solidity", "Ethereum", "Web3.js", "NFT", "DeFi"],
    languages: ["English"],
    responseTime: "within 12 hours",
  },
  {
    name: "Victoria Young",
    email: "victoria.young@skillbridge.dev",
    location: "Las Vegas, NV, USA",
    timezone: "America/Los_Angeles",
    tagline: "Motion Designer | 2D/3D Animation | Brand Films | Explainers",
    bio: "Motion designer creating high-quality animated brand films and product explainers. Clients include Shopify, Intercom, and 30+ Y Combinator startups.",
    hourlyRate: 95,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "victoriayoung.motion",
    categorySlug: "video-animation",
    skills: ["After Effects", "Motion Graphics", "2D Animation", "Adobe Premiere Pro", "Final Cut Pro"],
    languages: ["English"],
    responseTime: "within 4 hours",
  },
  {
    name: "Ethan King",
    email: "ethan.king@skillbridge.dev",
    location: "Indianapolis, IN, USA",
    timezone: "America/Indiana/Indianapolis",
    tagline: "App Security Engineer | SAST | DAST | Mobile Security",
    bio: "Application security engineer specializing in mobile and web app security assessments. Built automated security scanning pipelines integrated into CI/CD workflows.",
    hourlyRate: 130,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/ethanking-appsec",
    categorySlug: "cybersecurity",
    skills: ["Burp Suite", "OWASP", "Application Security", "SIEM", "Vulnerability Assessment"],
    languages: ["English"],
    responseTime: "within 6 hours",
  },
  {
    name: "Madison Wright",
    email: "madison.wright@skillbridge.dev",
    location: "Portland, ME, USA",
    timezone: "America/New_York",
    tagline: "Copywriter & Brand Voice Expert | SaaS | Fintech | VC-backed",
    bio: "Brand copywriter who has defined voice and tone for 20+ funded startups. Specializes in onboarding copy, landing pages, and email sequences that convert.",
    hourlyRate: 75,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "madisonwright.copy",
    categorySlug: "writing-content",
    skills: ["Copywriting", "UX Writing", "Content Strategy", "SEO Writing", "Ghost Writing"],
    languages: ["English"],
    responseTime: "within 2 hours",
  },
  {
    name: "Caleb Torres",
    email: "caleb.torres@skillbridge.dev",
    location: "El Paso, TX, USA",
    timezone: "America/Denver",
    tagline: "Indie Game Developer | Godot | 2D Pixel Art | Narrative Games",
    bio: "Indie game developer and Godot evangelist. Released 3 commercial games on Steam with combined 50K+ wishlists. Expert in procedural generation and narrative systems.",
    hourlyRate: 80,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/calebtorres-indie",
    categorySlug: "game-development",
    skills: ["Godot", "Unity", "2D Game Development", "Game Design", "Game Art & Assets"],
    languages: ["English", "Spanish"],
    responseTime: "within 6 hours",
  },
  {
    name: "Olivia Adams",
    email: "olivia.adams@skillbridge.dev",
    location: "Memphis, TN, USA",
    timezone: "America/Chicago",
    tagline: "PPC & Paid Social Expert | Google | Meta | TikTok Ads",
    bio: "Performance marketing specialist managing $2M+ in monthly ad spend across Google, Meta, and TikTok. Consistently achieves 3-5x ROAS for DTC e-commerce brands.",
    hourlyRate: 85,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/oliviaadams-ads",
    categorySlug: "digital-marketing",
    skills: ["Google Ads", "Facebook Ads", "SEO", "Analytics", "Affiliate Marketing"],
    languages: ["English"],
    responseTime: "within 3 hours",
  },
  {
    name: "Logan Nelson",
    email: "logan.nelson@skillbridge.dev",
    location: "Kansas City, MO, USA",
    timezone: "America/Chicago",
    tagline: "Go Developer | Cloud-Native | CLI Tools | Platform Engineering",
    bio: "Go developer building cloud-native tools, internal developer platforms, and high-performance CLIs. Open-source contributor with 3K+ GitHub followers.",
    hourlyRate: 120,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/logannelson-go",
    categorySlug: "software-development",
    skills: ["Go", "Rust", "gRPC", "Microservices", "RabbitMQ"],
    languages: ["English"],
    responseTime: "within 4 hours",
  },
  {
    name: "Gabrielle Mitchell",
    email: "gabrielle.mitchell@skillbridge.dev",
    location: "Oakland, CA, USA",
    timezone: "America/Los_Angeles",
    tagline: "3D Product Visualizer | Blender | Substance | Luxury Brands",
    bio: "3D artist and product visualizer working with luxury, beauty, and consumer electronics brands. Creates photorealistic renders used in global ad campaigns.",
    hourlyRate: 95,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "gabriellemitchell3d.com",
    categorySlug: "3d-ar-vr",
    skills: ["Blender", "Substance Painter", "Cinema 4D", "KeyShot", "3D Rendering & Visualization"],
    languages: ["English"],
    responseTime: "within 5 hours",
  },
  {
    name: "Zachary Perez",
    email: "zachary.perez@skillbridge.dev",
    location: "Tampa, FL, USA",
    timezone: "America/New_York",
    tagline: "Podcast Producer | Voice Over Director | Audio Branding",
    bio: "Podcast producer and audio branding expert who has launched and grown 15+ podcasts from zero to 50K+ listeners. Partner at three Top 100 podcast shows.",
    hourlyRate: 75,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    portfolio: "zacharyperez.audio",
    categorySlug: "audio-music",
    skills: ["Podcast Editing", "Pro Tools", "Voice Over", "Audio Branding", "Mastering"],
    languages: ["English", "Spanish"],
    responseTime: "within 4 hours",
  },
  {
    name: "Isabella Rivera",
    email: "isabella.rivera@skillbridge.dev",
    location: "Sacramento, CA, USA",
    timezone: "America/Los_Angeles",
    tagline: "Operations Consultant | Process Design | Notion | Asana",
    bio: "Operations consultant helping remote-first teams design scalable processes, OKR frameworks, and knowledge management systems. Former COO of a 50-person startup.",
    hourlyRate: 110,
    experienceLevel: ExperienceLevel.EXPERT,
    availability: AvailabilityStatus.AVAILABLE,
    linkedin: "linkedin.com/in/isabellarivera-ops",
    categorySlug: "business-consulting",
    skills: ["Business Strategy", "Project Management", "Agile", "Scrum", "Operations Consulting"],
    languages: ["English", "Spanish"],
    responseTime: "within 5 hours",
  },
  {
    name: "Mason Evans",
    email: "mason.evans@skillbridge.dev",
    location: "Baltimore, MD, USA",
    timezone: "America/New_York",
    tagline: "React Native & Expo Developer | Healthcare & Telehealth Apps",
    bio: "Mobile developer specialized in HIPAA-compliant healthcare and telehealth applications. Built real-time video consultation and EHR-integrated patient portals.",
    hourlyRate: 110,
    experienceLevel: ExperienceLevel.SENIOR,
    availability: AvailabilityStatus.AVAILABLE,
    github: "github.com/masonevans-mobile",
    categorySlug: "mobile-development",
    skills: ["React Native", "Expo", "Firebase", "Swift", "Redux"],
    languages: ["English"],
    responseTime: "within 4 hours",
  },
];

// ============================================================
// SEED FUNCTION
// ============================================================
export async function seedFreelancers() {
  console.log("🌱 Seeding 100 freelancers...\n");

  // Pre-load all categories and subcategories
  const allCategories = await prisma.category.findMany({
    include: { subCategories: true },
  });

  if (allCategories.length === 0) {
    throw new Error(
      "❌ No categories found. Please run the categories seed first:\n   npx prisma db seed (categories seed)"
    );
  }

  // Build slug → category map
  const categoryMap = new Map(allCategories.map((c) => [c.slug, c]));

  let successCount = 0;
  let skipCount = 0;

  for (const freelancer of FREELANCERS) {
    try {
      const category = categoryMap.get(freelancer.categorySlug);
      if (!category) {
        console.warn(`⚠️  Category not found for slug: ${freelancer.categorySlug} — skipping ${freelancer.name}`);
        skipCount++;
        continue;
      }

      const passwordHash = await bcrypt.hash("Password@123", 10);

      // 1. Upsert User
      const user = await prisma.user.upsert({
        where: { email: freelancer.email },
        update: {},
        create: {
          name: freelancer.name,
          email: freelancer.email,
          passwordHash,
          role: Role.FREELANCER,
          isEmailVerified: true,
          profileImage: `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(freelancer.name)}`,
        },
      });

      // 2. Upsert FreelancerProfile
      const profile = await prisma.freelancerProfile.upsert({
        where: { userId: user.id },
        update: {
          tagline: freelancer.tagline,
          bio: freelancer.bio,
          hourlyRate: freelancer.hourlyRate,
          experienceLevel: freelancer.experienceLevel,
          availability: freelancer.availability,
          location: freelancer.location,
          timezone: freelancer.timezone,
          languages: freelancer.languages,
          responseTime: freelancer.responseTime,
          github: freelancer.github ?? null,
          linkedin: freelancer.linkedin ?? null,
          portfolio: freelancer.portfolio ?? null,
          profileCompletion: 85,
        },
        create: {
          userId: user.id,
          fullName: freelancer.name,
          tagline: freelancer.tagline,
          bio: freelancer.bio,
          hourlyRate: freelancer.hourlyRate,
          experienceLevel: freelancer.experienceLevel,
          availability: freelancer.availability,
          location: freelancer.location,
          timezone: freelancer.timezone,
          languages: freelancer.languages,
          responseTime: freelancer.responseTime,
          github: freelancer.github ?? null,
          linkedin: freelancer.linkedin ?? null,
          portfolio: freelancer.portfolio ?? null,
          website: (freelancer as any).website ?? null,
          profileCompletion: 85,
        },
      });

      // 3. Upsert Skills and link to FreelancerProfile
      for (const skillName of freelancer.skills) {
        // Upsert the global Skill record
        const skill = await prisma.skill.upsert({
          where: { name: skillName },
          update: {},
          create: {
            name: skillName,
            category: category.name,
          },
        });

        // Link skill to freelancer profile (ignore if already linked)
        const existing = await prisma.freelancerSkill.findUnique({
          where: {
            freelancerProfileId_skillId: {
              freelancerProfileId: profile.id,
              skillId: skill.id,
            },
          },
        });

        if (!existing) {
          await prisma.freelancerSkill.create({
            data: {
              freelancerProfileId: profile.id,
              skillId: skill.id,
              proficiencyLevel: Math.floor(Math.random() * 2) + 4, // 4 or 5
            },
          });
        }
      }

      successCount++;
      console.log(`✅ ${freelancer.name} (${freelancer.location})`);
    } catch (err: any) {
      console.error(`❌ Failed to seed ${freelancer.name}:`, err.message);
      skipCount++;
    }
  }

  console.log("\n────────────────────────────────────────");
  console.log(`✅ Successfully seeded: ${successCount} freelancers`);
  if (skipCount > 0) console.log(`⚠️  Skipped: ${skipCount}`);
  console.log("────────────────────────────────────────");
  console.log("🔑 All accounts password: Password@123");
}

async function main() {
  await seedFreelancers();
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

