import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding metadata...");

  // Languages
  const languages = [
    { name: "English", code: "en" },
    { name: "Spanish", code: "es" },
    { name: "French", code: "fr" },
    { name: "German", code: "de" },
    { name: "Italian", code: "it" },
    { name: "Portuguese", code: "pt" },
    { name: "Russian", code: "ru" },
    { name: "Mandarin Chinese", code: "zh" },
    { name: "Cantonese", code: "yue" },
    { name: "Japanese", code: "ja" },
    { name: "Korean", code: "ko" },
    { name: "Hindi", code: "hi" },
    { name: "Urdu", code: "ur" },
    { name: "Bengali", code: "bn" },
    { name: "Punjabi", code: "pa" },
    { name: "Turkish", code: "tr" },
    { name: "Arabic", code: "ar" },
    { name: "Persian", code: "fa" },
    { name: "Hebrew", code: "he" },
    { name: "Indonesian", code: "id" },
    { name: "Malay", code: "ms" },
    { name: "Thai", code: "th" },
    { name: "Vietnamese", code: "vi" },
    { name: "Filipino", code: "tl" },
    { name: "Polish", code: "pl" },
    { name: "Dutch", code: "nl" },
    { name: "Swedish", code: "sv" },
    { name: "Norwegian", code: "no" },
    { name: "Danish", code: "da" },
    { name: "Finnish", code: "fi" },
    { name: "Greek", code: "el" },
    { name: "Czech", code: "cs" },
    { name: "Hungarian", code: "hu" },
    { name: "Romanian", code: "ro" },
    { name: "Ukrainian", code: "uk" },
    { name: "Swahili", code: "sw" },
    { name: "Afrikaans", code: "af" },
  ];

  for (const lang of languages) {
    try {
      await prisma.language.upsert({
        where: { name: lang.name },
        update: { code: lang.code },
        create: lang,
      });
    } catch (e) {
      console.warn(`Skipping duplicate language: ${lang.name} (${lang.code})`);
    }
  }

  // Locations
  const locations = [
    { name: "Any location", region: "Global", phoneCode: "" },
    { name: "Afghanistan", region: "Asia", phoneCode: "93" },
    { name: "Albania", region: "Europe", phoneCode: "355" },
    { name: "Algeria", region: "Africa", phoneCode: "213" },
    { name: "American Samoa", region: "Oceania", phoneCode: "1684" },
    { name: "Andorra", region: "Europe", phoneCode: "376" },
    { name: "Angola", region: "Africa", phoneCode: "244" },
    { name: "Anguilla", region: "Americas", phoneCode: "1264" },
    { name: "Antarctica", region: "Antarctic", phoneCode: "" },
    { name: "Antigua and Barbuda", region: "Americas", phoneCode: "1268" },
    { name: "Argentina", region: "Americas", phoneCode: "54" },
    { name: "Armenia", region: "Asia", phoneCode: "374" },
    { name: "Aruba", region: "Americas", phoneCode: "297" },
    { name: "Australia", region: "Oceania", phoneCode: "61" },
    { name: "Austria", region: "Europe", phoneCode: "43" },
    { name: "Azerbaijan", region: "Asia", phoneCode: "994" },
    { name: "Bahamas", region: "Americas", phoneCode: "1242" },
    { name: "Bahrain", region: "Middle East", phoneCode: "973" },
    { name: "Bangladesh", region: "Asia", phoneCode: "880" },
    { name: "Barbados", region: "Americas", phoneCode: "1246" },
    { name: "Belarus", region: "Europe", phoneCode: "375" },
    { name: "Belgium", region: "Europe", phoneCode: "32" },
    { name: "Belize", region: "Americas", phoneCode: "501" },
    { name: "Benin", region: "Africa", phoneCode: "229" },
    { name: "Bermuda", region: "Americas", phoneCode: "1441" },
    { name: "Bhutan", region: "Asia", phoneCode: "975" },
    { name: "Bolivia", region: "Americas", phoneCode: "591" },
    { name: "Bosnia and Herzegovina", region: "Europe", phoneCode: "387" },
    { name: "Botswana", region: "Africa", phoneCode: "267" },
    { name: "Bouvet Island", region: "Antarctic", phoneCode: "47" },
    { name: "Brazil", region: "Americas", phoneCode: "55" },
    { name: "British Indian Ocean Territory", region: "Africa", phoneCode: "246" },
    { name: "British Virgin Islands", region: "Americas", phoneCode: "1284" },
    { name: "Brunei", region: "Asia", phoneCode: "673" },
    { name: "Bulgaria", region: "Europe", phoneCode: "359" },
    { name: "Burkina Faso", region: "Africa", phoneCode: "226" },
    { name: "Burundi", region: "Africa", phoneCode: "257" },
    { name: "Cambodia", region: "Asia", phoneCode: "855" },
    { name: "Cameroon", region: "Africa", phoneCode: "237" },
    { name: "Canada", region: "Americas", phoneCode: "1" },
    { name: "Cape Verde", region: "Africa", phoneCode: "238" },
    { name: "Caribbean Netherlands", region: "Americas", phoneCode: "599" },
    { name: "Cayman Islands", region: "Americas", phoneCode: "1345" },
    { name: "Central African Republic", region: "Africa", phoneCode: "236" },
    { name: "Chad", region: "Africa", phoneCode: "235" },
    { name: "Chile", region: "Americas", phoneCode: "56" },
    { name: "China", region: "Asia", phoneCode: "86" },
    { name: "Christmas Island", region: "Oceania", phoneCode: "61" },
    { name: "Cocos (Keeling) Islands", region: "Oceania", phoneCode: "61" },
    { name: "Colombia", region: "Americas", phoneCode: "57" },
    { name: "Comoros", region: "Africa", phoneCode: "269" },
    { name: "Congo", region: "Africa", phoneCode: "242" },
    { name: "Cook Islands", region: "Oceania", phoneCode: "682" },
    { name: "Costa Rica", region: "Americas", phoneCode: "506" },
    { name: "Croatia", region: "Europe", phoneCode: "385" },
    { name: "Cuba", region: "Americas", phoneCode: "53" },
    { name: "Curaçao", region: "Americas", phoneCode: "599" },
    { name: "Cyprus", region: "Europe", phoneCode: "357" },
    { name: "Czechia", region: "Europe", phoneCode: "420" },
    { name: "DR Congo", region: "Africa", phoneCode: "243" },
    { name: "Denmark", region: "Europe", phoneCode: "45" },
    { name: "Djibouti", region: "Africa", phoneCode: "253" },
    { name: "Dominica", region: "Americas", phoneCode: "1767" },
    { name: "Dominican Republic", region: "Americas", phoneCode: "1" },
    { name: "Ecuador", region: "Americas", phoneCode: "593" },
    { name: "Egypt", region: "Middle East", phoneCode: "20" },
    { name: "El Salvador", region: "Americas", phoneCode: "503" },
    { name: "Equatorial Guinea", region: "Africa", phoneCode: "240" },
    { name: "Eritrea", region: "Africa", phoneCode: "291" },
    { name: "Estonia", region: "Europe", phoneCode: "372" },
    { name: "Eswatini", region: "Africa", phoneCode: "268" },
    { name: "Ethiopia", region: "Africa", phoneCode: "251" },
    { name: "Falkland Islands", region: "Americas", phoneCode: "500" },
    { name: "Faroe Islands", region: "Europe", phoneCode: "298" },
    { name: "Fiji", region: "Oceania", phoneCode: "679" },
    { name: "Finland", region: "Europe", phoneCode: "358" },
    { name: "France", region: "Europe", phoneCode: "33" },
    { name: "French Guiana", region: "Americas", phoneCode: "594" },
    { name: "French Polynesia", region: "Oceania", phoneCode: "689" },
    { name: "French Southern and Antarctic Lands", region: "Antarctic", phoneCode: "262" },
    { name: "Gabon", region: "Africa", phoneCode: "241" },
    { name: "Gambia", region: "Africa", phoneCode: "220" },
    { name: "Georgia", region: "Asia", phoneCode: "995" },
    { name: "Germany", region: "Europe", phoneCode: "49" },
    { name: "Ghana", region: "Africa", phoneCode: "233" },
    { name: "Gibraltar", region: "Europe", phoneCode: "350" },
    { name: "Greece", region: "Europe", phoneCode: "30" },
    { name: "Greenland", region: "Americas", phoneCode: "299" },
    { name: "Grenada", region: "Americas", phoneCode: "1473" },
    { name: "Guadeloupe", region: "Americas", phoneCode: "590" },
    { name: "Guam", region: "Oceania", phoneCode: "1671" },
    { name: "Guatemala", region: "Americas", phoneCode: "502" },
    { name: "Guernsey", region: "Europe", phoneCode: "44" },
    { name: "Guinea", region: "Africa", phoneCode: "224" },
    { name: "Guinea-Bissau", region: "Africa", phoneCode: "245" },
    { name: "Guyana", region: "Americas", phoneCode: "592" },
    { name: "Haiti", region: "Americas", phoneCode: "509" },
    { name: "Heard Island and McDonald Islands", region: "Antarctic", phoneCode: "" },
    { name: "Honduras", region: "Americas", phoneCode: "504" },
    { name: "Hong Kong", region: "Asia", phoneCode: "852" },
    { name: "Hungary", region: "Europe", phoneCode: "36" },
    { name: "Iceland", region: "Europe", phoneCode: "354" },
    { name: "India", region: "Asia", phoneCode: "91" },
    { name: "Indonesia", region: "Asia", phoneCode: "62" },
    { name: "Iran", region: "Asia", phoneCode: "98" },
    { name: "Iraq", region: "Middle East", phoneCode: "964" },
    { name: "Ireland", region: "Europe", phoneCode: "353" },
    { name: "Isle of Man", region: "Europe", phoneCode: "44" },
    { name: "Israel", region: "Middle East", phoneCode: "972" },
    { name: "Italy", region: "Europe", phoneCode: "39" },
    { name: "Ivory Coast", region: "Africa", phoneCode: "225" },
    { name: "Jamaica", region: "Americas", phoneCode: "1876" },
    { name: "Japan", region: "Asia", phoneCode: "81" },
    { name: "Jersey", region: "Europe", phoneCode: "44" },
    { name: "Jordan", region: "Middle East", phoneCode: "962" },
    { name: "Kazakhstan", region: "Asia", phoneCode: "7" },
    { name: "Kenya", region: "Africa", phoneCode: "254" },
    { name: "Kiribati", region: "Oceania", phoneCode: "686" },
    { name: "Kosovo", region: "Europe", phoneCode: "383" },
    { name: "Kuwait", region: "Middle East", phoneCode: "965" },
    { name: "Kyrgyzstan", region: "Asia", phoneCode: "996" },
    { name: "Laos", region: "Asia", phoneCode: "856" },
    { name: "Latvia", region: "Europe", phoneCode: "371" },
    { name: "Lebanon", region: "Middle East", phoneCode: "961" },
    { name: "Lesotho", region: "Africa", phoneCode: "266" },
    { name: "Liberia", region: "Africa", phoneCode: "231" },
    { name: "Libya", region: "Africa", phoneCode: "218" },
    { name: "Liechtenstein", region: "Europe", phoneCode: "423" },
    { name: "Lithuania", region: "Europe", phoneCode: "370" },
    { name: "Luxembourg", region: "Europe", phoneCode: "352" },
    { name: "Macau", region: "Asia", phoneCode: "853" },
    { name: "Madagascar", region: "Africa", phoneCode: "261" },
    { name: "Malawi", region: "Africa", phoneCode: "265" },
    { name: "Malaysia", region: "Asia", phoneCode: "60" },
    { name: "Maldives", region: "Asia", phoneCode: "960" },
    { name: "Mali", region: "Africa", phoneCode: "223" },
    { name: "Malta", region: "Europe", phoneCode: "356" },
    { name: "Marshall Islands", region: "Oceania", phoneCode: "692" },
    { name: "Martinique", region: "Americas", phoneCode: "596" },
    { name: "Mauritania", region: "Africa", phoneCode: "222" },
    { name: "Mauritius", region: "Africa", phoneCode: "230" },
    { name: "Mayotte", region: "Africa", phoneCode: "262" },
    { name: "Mexico", region: "Americas", phoneCode: "52" },
    { name: "Micronesia", region: "Oceania", phoneCode: "691" },
    { name: "Moldova", region: "Europe", phoneCode: "373" },
    { name: "Monaco", region: "Europe", phoneCode: "377" },
    { name: "Mongolia", region: "Asia", phoneCode: "976" },
    { name: "Montenegro", region: "Europe", phoneCode: "382" },
    { name: "Montserrat", region: "Americas", phoneCode: "1664" },
    { name: "Morocco", region: "Africa", phoneCode: "212" },
    { name: "Mozambique", region: "Africa", phoneCode: "258" },
    { name: "Myanmar", region: "Asia", phoneCode: "95" },
    { name: "Namibia", region: "Africa", phoneCode: "264" },
    { name: "Nauru", region: "Oceania", phoneCode: "674" },
    { name: "Nepal", region: "Asia", phoneCode: "977" },
    { name: "Netherlands", region: "Europe", phoneCode: "31" },
    { name: "New Caledonia", region: "Oceania", phoneCode: "687" },
    { name: "New Zealand", region: "Oceania", phoneCode: "64" },
    { name: "Nicaragua", region: "Americas", phoneCode: "505" },
    { name: "Niger", region: "Africa", phoneCode: "227" },
    { name: "Nigeria", region: "Africa", phoneCode: "234" },
    { name: "Niue", region: "Oceania", phoneCode: "683" },
    { name: "Norfolk Island", region: "Oceania", phoneCode: "672" },
    { name: "North Korea", region: "Asia", phoneCode: "850" },
    { name: "North Macedonia", region: "Europe", phoneCode: "389" },
    { name: "Northern Mariana Islands", region: "Oceania", phoneCode: "1670" },
    { name: "Norway", region: "Europe", phoneCode: "47" },
    { name: "Oman", region: "Middle East", phoneCode: "968" },
    { name: "Pakistan", region: "Asia", phoneCode: "92" },
    { name: "Palau", region: "Oceania", phoneCode: "680" },
    { name: "Palestine", region: "Middle East", phoneCode: "970" },
    { name: "Panama", region: "Americas", phoneCode: "507" },
    { name: "Papua New Guinea", region: "Oceania", phoneCode: "675" },
    { name: "Paraguay", region: "Americas", phoneCode: "595" },
    { name: "Peru", region: "Americas", phoneCode: "51" },
    { name: "Philippines", region: "Asia", phoneCode: "63" },
    { name: "Pitcairn Islands", region: "Oceania", phoneCode: "64" },
    { name: "Poland", region: "Europe", phoneCode: "48" },
    { name: "Portugal", region: "Europe", phoneCode: "351" },
    { name: "Puerto Rico", region: "Americas", phoneCode: "1" },
    { name: "Qatar", region: "Middle East", phoneCode: "974" },
    { name: "Romania", region: "Europe", phoneCode: "40" },
    { name: "Russia", region: "Europe", phoneCode: "7" },
    { name: "Rwanda", region: "Africa", phoneCode: "250" },
    { name: "Réunion", region: "Africa", phoneCode: "262" },
    { name: "Saint Barthélemy", region: "Americas", phoneCode: "590" },
    { name: "Saint Helena, Ascension and Tristan da Cunha", region: "Africa", phoneCode: "2" },
    { name: "Saint Kitts and Nevis", region: "Americas", phoneCode: "1869" },
    { name: "Saint Lucia", region: "Americas", phoneCode: "1758" },
    { name: "Saint Martin", region: "Americas", phoneCode: "590" },
    { name: "Saint Pierre and Miquelon", region: "Americas", phoneCode: "508" },
    { name: "Saint Vincent and the Grenadines", region: "Americas", phoneCode: "1784" },
    { name: "Samoa", region: "Oceania", phoneCode: "685" },
    { name: "San Marino", region: "Europe", phoneCode: "378" },
    { name: "Saudi Arabia", region: "Middle East", phoneCode: "966" },
    { name: "Senegal", region: "Africa", phoneCode: "221" },
    { name: "Serbia", region: "Europe", phoneCode: "381" },
    { name: "Seychelles", region: "Africa", phoneCode: "248" },
    { name: "Sierra Leone", region: "Africa", phoneCode: "232" },
    { name: "Singapore", region: "Asia", phoneCode: "65" },
    { name: "Sint Maarten", region: "Americas", phoneCode: "1721" },
    { name: "Slovakia", region: "Europe", phoneCode: "421" },
    { name: "Slovenia", region: "Europe", phoneCode: "386" },
    { name: "Solomon Islands", region: "Oceania", phoneCode: "677" },
    { name: "Somalia", region: "Africa", phoneCode: "252" },
    { name: "South Africa", region: "Africa", phoneCode: "27" },
    { name: "South Georgia", region: "Antarctic", phoneCode: "500" },
    { name: "South Korea", region: "Asia", phoneCode: "82" },
    { name: "South Sudan", region: "Africa", phoneCode: "211" },
    { name: "Spain", region: "Europe", phoneCode: "34" },
    { name: "Sri Lanka", region: "Asia", phoneCode: "94" },
    { name: "Sudan", region: "Africa", phoneCode: "249" },
    { name: "Suriname", region: "Americas", phoneCode: "597" },
    { name: "Svalbard and Jan Mayen", region: "Europe", phoneCode: "4779" },
    { name: "Sweden", region: "Europe", phoneCode: "46" },
    { name: "Switzerland", region: "Europe", phoneCode: "41" },
    { name: "Syria", region: "Asia", phoneCode: "963" },
    { name: "São Tomé and Príncipe", region: "Africa", phoneCode: "239" },
    { name: "Taiwan", region: "Asia", phoneCode: "886" },
    { name: "Tajikistan", region: "Asia", phoneCode: "992" },
    { name: "Tanzania", region: "Africa", phoneCode: "255" },
    { name: "Thailand", region: "Asia", phoneCode: "66" },
    { name: "Timor-Leste", region: "Asia", phoneCode: "670" },
    { name: "Togo", region: "Africa", phoneCode: "228" },
    { name: "Tokelau", region: "Oceania", phoneCode: "690" },
    { name: "Tonga", region: "Oceania", phoneCode: "676" },
    { name: "Trinidad and Tobago", region: "Americas", phoneCode: "1868" },
    { name: "Tunisia", region: "Africa", phoneCode: "216" },
    { name: "Turkmenistan", region: "Asia", phoneCode: "993" },
    { name: "Turks and Caicos Islands", region: "Americas", phoneCode: "1649" },
    { name: "Tuvalu", region: "Oceania", phoneCode: "688" },
    { name: "Türkiye", region: "Asia", phoneCode: "90" },
    { name: "Uganda", region: "Africa", phoneCode: "256" },
    { name: "Ukraine", region: "Europe", phoneCode: "380" },
    { name: "United Arab Emirates", region: "Middle East", phoneCode: "971" },
    { name: "United Kingdom", region: "Europe", phoneCode: "44" },
    { name: "United States", region: "Americas", phoneCode: "1" },
    { name: "United States Minor Outlying Islands", region: "Americas", phoneCode: "268" },
    { name: "United States Virgin Islands", region: "Americas", phoneCode: "1340" },
    { name: "Uruguay", region: "Americas", phoneCode: "598" },
    { name: "Uzbekistan", region: "Asia", phoneCode: "998" },
    { name: "Vanuatu", region: "Oceania", phoneCode: "678" },
    { name: "Vatican City", region: "Europe", phoneCode: "3" },
    { name: "Venezuela", region: "Americas", phoneCode: "58" },
    { name: "Vietnam", region: "Asia", phoneCode: "84" },
    { name: "Wallis and Futuna", region: "Oceania", phoneCode: "681" },
    { name: "Western Sahara", region: "Africa", phoneCode: "2" },
    { name: "Yemen", region: "Asia", phoneCode: "967" },
    { name: "Zambia", region: "Africa", phoneCode: "260" },
    { name: "Zimbabwe", region: "Africa", phoneCode: "263" },
    { name: "Åland Islands", region: "Europe", phoneCode: "35818" },
  ];

  for (const loc of locations) {
    await prisma.location.upsert({
      where: { name: loc.name },
      update: { phoneCode: loc.phoneCode },
      create: loc,
    });
  }

  console.log("✅ Metadata seeding completed.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
